# Generated by Django 5.2.6 on 2025-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="task_attachments/"
            ),
        ),
    ]
